import { Injectable, Logger } from '@nestjs/common';
import { StatsFeedClient } from '../grid/clients/stats-feed.client';
import { CacheService } from '../cache/cache.service';

// All League of Legends champions for draft (complete roster)
// Images use Data Dragon CDN: https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/
const DDRAGON_VERSION = '14.1.1';
const getChampionImage = (name: string) =>
  `https://ddragon.leagueoflegends.com/cdn/${DDRAGON_VERSION}/img/champion/${name}.png`;

const CHAMPIONS = [
  {
    id: 'aatrox',
    name: 'Aatrox',
    roles: ['TOP'],
    image: getChampionImage('Aatrox'),
  },
  { id: 'ahri', name: 'Ahri', roles: ['MID'], image: getChampionImage('Ahri') },
  {
    id: 'akali',
    name: 'Akali',
    roles: ['MID', 'TOP'],
    image: getChampionImage('Akali'),
  },
  {
    id: 'akshan',
    name: 'Akshan',
    roles: ['MID', 'TOP'],
    image: getChampionImage('Akshan'),
  },
  {
    id: 'alistar',
    name: 'Alistar',
    roles: ['SUP'],
    image: getChampionImage('Alistar'),
  },
  {
    id: 'amumu',
    name: 'Amumu',
    roles: ['JGL', 'SUP'],
    image: getChampionImage('Amumu'),
  },
  {
    id: 'anivia',
    name: 'Anivia',
    roles: ['MID'],
    image: getChampionImage('Anivia'),
  },
  {
    id: 'annie',
    name: 'Annie',
    roles: ['MID', 'SUP'],
    image: getChampionImage('Annie'),
  },
  {
    id: 'aphelios',
    name: 'Aphelios',
    roles: ['ADC'],
    image: getChampionImage('Aphelios'),
  },
  {
    id: 'ashe',
    name: 'Ashe',
    roles: ['ADC', 'SUP'],
    image: getChampionImage('Ashe'),
  },
  {
    id: 'aurelionsol',
    name: 'Aurelion Sol',
    roles: ['MID'],
    image: getChampionImage('AurelionSol'),
  },
  { id: 'azir', name: 'Azir', roles: ['MID'], image: getChampionImage('Azir') },
  { id: 'bard', name: 'Bard', roles: ['SUP'], image: getChampionImage('Bard') },
  {
    id: 'belveth',
    name: "Bel'Veth",
    roles: ['JGL'],
    image: getChampionImage('Belveth'),
  },
  {
    id: 'blitzcrank',
    name: 'Blitzcrank',
    roles: ['SUP'],
    image: getChampionImage('Blitzcrank'),
  },
  {
    id: 'brand',
    name: 'Brand',
    roles: ['SUP', 'MID'],
    image: getChampionImage('Brand'),
  },
  {
    id: 'braum',
    name: 'Braum',
    roles: ['SUP'],
    image: getChampionImage('Braum'),
  },
  {
    id: 'briar',
    name: 'Briar',
    roles: ['JGL'],
    image: getChampionImage('Briar'),
  },
  {
    id: 'caitlyn',
    name: 'Caitlyn',
    roles: ['ADC'],
    image: getChampionImage('Caitlyn'),
  },
  {
    id: 'camille',
    name: 'Camille',
    roles: ['TOP'],
    image: getChampionImage('Camille'),
  },
  {
    id: 'cassiopeia',
    name: 'Cassiopeia',
    roles: ['MID'],
    image: getChampionImage('Cassiopeia'),
  },
  {
    id: 'chogath',
    name: "Cho'Gath",
    roles: ['TOP', 'MID'],
    image: getChampionImage('Chogath'),
  },
  {
    id: 'corki',
    name: 'Corki',
    roles: ['MID'],
    image: getChampionImage('Corki'),
  },
  {
    id: 'darius',
    name: 'Darius',
    roles: ['TOP'],
    image: getChampionImage('Darius'),
  },
  {
    id: 'diana',
    name: 'Diana',
    roles: ['JGL', 'MID'],
    image: getChampionImage('Diana'),
  },
  {
    id: 'draven',
    name: 'Draven',
    roles: ['ADC'],
    image: getChampionImage('Draven'),
  },
  {
    id: 'drmundo',
    name: 'Dr. Mundo',
    roles: ['TOP', 'JGL'],
    image: getChampionImage('DrMundo'),
  },
  {
    id: 'ekko',
    name: 'Ekko',
    roles: ['MID', 'JGL'],
    image: getChampionImage('Ekko'),
  },
  {
    id: 'elise',
    name: 'Elise',
    roles: ['JGL'],
    image: getChampionImage('Elise'),
  },
  {
    id: 'evelynn',
    name: 'Evelynn',
    roles: ['JGL'],
    image: getChampionImage('Evelynn'),
  },
  {
    id: 'ezreal',
    name: 'Ezreal',
    roles: ['ADC'],
    image: getChampionImage('Ezreal'),
  },
  {
    id: 'fiddlesticks',
    name: 'Fiddlesticks',
    roles: ['JGL'],
    image: getChampionImage('Fiddlesticks'),
  },
  {
    id: 'fiora',
    name: 'Fiora',
    roles: ['TOP'],
    image: getChampionImage('Fiora'),
  },
  { id: 'fizz', name: 'Fizz', roles: ['MID'], image: getChampionImage('Fizz') },
  {
    id: 'galio',
    name: 'Galio',
    roles: ['MID', 'SUP'],
    image: getChampionImage('Galio'),
  },
  {
    id: 'gangplank',
    name: 'Gangplank',
    roles: ['TOP', 'MID'],
    image: getChampionImage('Gangplank'),
  },
  {
    id: 'garen',
    name: 'Garen',
    roles: ['TOP'],
    image: getChampionImage('Garen'),
  },
  { id: 'gnar', name: 'Gnar', roles: ['TOP'], image: getChampionImage('Gnar') },
  {
    id: 'gragas',
    name: 'Gragas',
    roles: ['JGL', 'TOP', 'MID'],
    image: getChampionImage('Gragas'),
  },
  {
    id: 'graves',
    name: 'Graves',
    roles: ['JGL'],
    image: getChampionImage('Graves'),
  },
  { id: 'gwen', name: 'Gwen', roles: ['TOP'], image: getChampionImage('Gwen') },
  {
    id: 'hecarim',
    name: 'Hecarim',
    roles: ['JGL'],
    image: getChampionImage('Hecarim'),
  },
  {
    id: 'heimerdinger',
    name: 'Heimerdinger',
    roles: ['MID', 'TOP', 'SUP'],
    image: getChampionImage('Heimerdinger'),
  },
  {
    id: 'hwei',
    name: 'Hwei',
    roles: ['MID', 'SUP'],
    image: getChampionImage('Hwei'),
  },
  {
    id: 'illaoi',
    name: 'Illaoi',
    roles: ['TOP'],
    image: getChampionImage('Illaoi'),
  },
  {
    id: 'irelia',
    name: 'Irelia',
    roles: ['TOP', 'MID'],
    image: getChampionImage('Irelia'),
  },
  {
    id: 'ivern',
    name: 'Ivern',
    roles: ['JGL'],
    image: getChampionImage('Ivern'),
  },
  {
    id: 'janna',
    name: 'Janna',
    roles: ['SUP'],
    image: getChampionImage('Janna'),
  },
  {
    id: 'jarvaniv',
    name: 'Jarvan IV',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('JarvanIV'),
  },
  {
    id: 'jax',
    name: 'Jax',
    roles: ['TOP', 'JGL'],
    image: getChampionImage('Jax'),
  },
  {
    id: 'jayce',
    name: 'Jayce',
    roles: ['TOP', 'MID'],
    image: getChampionImage('Jayce'),
  },
  { id: 'jhin', name: 'Jhin', roles: ['ADC'], image: getChampionImage('Jhin') },
  { id: 'jinx', name: 'Jinx', roles: ['ADC'], image: getChampionImage('Jinx') },
  {
    id: 'kaisa',
    name: "Kai'Sa",
    roles: ['ADC'],
    image: getChampionImage('Kaisa'),
  },
  {
    id: 'kalista',
    name: 'Kalista',
    roles: ['ADC'],
    image: getChampionImage('Kalista'),
  },
  {
    id: 'karma',
    name: 'Karma',
    roles: ['SUP', 'MID'],
    image: getChampionImage('Karma'),
  },
  {
    id: 'karthus',
    name: 'Karthus',
    roles: ['JGL', 'MID'],
    image: getChampionImage('Karthus'),
  },
  {
    id: 'kassadin',
    name: 'Kassadin',
    roles: ['MID'],
    image: getChampionImage('Kassadin'),
  },
  {
    id: 'katarina',
    name: 'Katarina',
    roles: ['MID'],
    image: getChampionImage('Katarina'),
  },
  {
    id: 'kayle',
    name: 'Kayle',
    roles: ['TOP', 'MID'],
    image: getChampionImage('Kayle'),
  },
  { id: 'kayn', name: 'Kayn', roles: ['JGL'], image: getChampionImage('Kayn') },
  {
    id: 'kennen',
    name: 'Kennen',
    roles: ['TOP'],
    image: getChampionImage('Kennen'),
  },
  {
    id: 'khazix',
    name: "Kha'Zix",
    roles: ['JGL'],
    image: getChampionImage('Khazix'),
  },
  {
    id: 'kindred',
    name: 'Kindred',
    roles: ['JGL'],
    image: getChampionImage('Kindred'),
  },
  { id: 'kled', name: 'Kled', roles: ['TOP'], image: getChampionImage('Kled') },
  {
    id: 'kogmaw',
    name: "Kog'Maw",
    roles: ['ADC'],
    image: getChampionImage('KogMaw'),
  },
  {
    id: 'ksante',
    name: "K'Sante",
    roles: ['TOP'],
    image: getChampionImage('KSante'),
  },
  {
    id: 'leblanc',
    name: 'LeBlanc',
    roles: ['MID'],
    image: getChampionImage('Leblanc'),
  },
  {
    id: 'leesin',
    name: 'Lee Sin',
    roles: ['JGL'],
    image: getChampionImage('LeeSin'),
  },
  {
    id: 'leona',
    name: 'Leona',
    roles: ['SUP'],
    image: getChampionImage('Leona'),
  },
  {
    id: 'lillia',
    name: 'Lillia',
    roles: ['JGL'],
    image: getChampionImage('Lillia'),
  },
  {
    id: 'lissandra',
    name: 'Lissandra',
    roles: ['MID'],
    image: getChampionImage('Lissandra'),
  },
  {
    id: 'lucian',
    name: 'Lucian',
    roles: ['ADC', 'MID'],
    image: getChampionImage('Lucian'),
  },
  { id: 'lulu', name: 'Lulu', roles: ['SUP'], image: getChampionImage('Lulu') },
  {
    id: 'lux',
    name: 'Lux',
    roles: ['SUP', 'MID'],
    image: getChampionImage('Lux'),
  },
  {
    id: 'malphite',
    name: 'Malphite',
    roles: ['TOP', 'SUP'],
    image: getChampionImage('Malphite'),
  },
  {
    id: 'malzahar',
    name: 'Malzahar',
    roles: ['MID'],
    image: getChampionImage('Malzahar'),
  },
  {
    id: 'maokai',
    name: 'Maokai',
    roles: ['SUP', 'JGL', 'TOP'],
    image: getChampionImage('Maokai'),
  },
  {
    id: 'masteryi',
    name: 'Master Yi',
    roles: ['JGL'],
    image: getChampionImage('MasterYi'),
  },
  {
    id: 'milio',
    name: 'Milio',
    roles: ['SUP'],
    image: getChampionImage('Milio'),
  },
  {
    id: 'missfortune',
    name: 'Miss Fortune',
    roles: ['ADC'],
    image: getChampionImage('MissFortune'),
  },
  {
    id: 'mordekaiser',
    name: 'Mordekaiser',
    roles: ['TOP'],
    image: getChampionImage('Mordekaiser'),
  },
  {
    id: 'morgana',
    name: 'Morgana',
    roles: ['SUP', 'MID'],
    image: getChampionImage('Morgana'),
  },
  {
    id: 'naafiri',
    name: 'Naafiri',
    roles: ['MID', 'JGL'],
    image: getChampionImage('Naafiri'),
  },
  { id: 'nami', name: 'Nami', roles: ['SUP'], image: getChampionImage('Nami') },
  {
    id: 'nasus',
    name: 'Nasus',
    roles: ['TOP'],
    image: getChampionImage('Nasus'),
  },
  {
    id: 'nautilus',
    name: 'Nautilus',
    roles: ['SUP'],
    image: getChampionImage('Nautilus'),
  },
  {
    id: 'neeko',
    name: 'Neeko',
    roles: ['MID', 'SUP'],
    image: getChampionImage('Neeko'),
  },
  {
    id: 'nidalee',
    name: 'Nidalee',
    roles: ['JGL'],
    image: getChampionImage('Nidalee'),
  },
  {
    id: 'nilah',
    name: 'Nilah',
    roles: ['ADC'],
    image: getChampionImage('Nilah'),
  },
  {
    id: 'nocturne',
    name: 'Nocturne',
    roles: ['JGL'],
    image: getChampionImage('Nocturne'),
  },
  {
    id: 'nunu',
    name: 'Nunu & Willump',
    roles: ['JGL'],
    image: getChampionImage('Nunu'),
  },
  {
    id: 'olaf',
    name: 'Olaf',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('Olaf'),
  },
  {
    id: 'orianna',
    name: 'Orianna',
    roles: ['MID'],
    image: getChampionImage('Orianna'),
  },
  { id: 'ornn', name: 'Ornn', roles: ['TOP'], image: getChampionImage('Ornn') },
  {
    id: 'pantheon',
    name: 'Pantheon',
    roles: ['TOP', 'MID', 'SUP'],
    image: getChampionImage('Pantheon'),
  },
  {
    id: 'poppy',
    name: 'Poppy',
    roles: ['JGL', 'TOP', 'SUP'],
    image: getChampionImage('Poppy'),
  },
  { id: 'pyke', name: 'Pyke', roles: ['SUP'], image: getChampionImage('Pyke') },
  {
    id: 'qiyana',
    name: 'Qiyana',
    roles: ['MID'],
    image: getChampionImage('Qiyana'),
  },
  {
    id: 'quinn',
    name: 'Quinn',
    roles: ['TOP'],
    image: getChampionImage('Quinn'),
  },
  {
    id: 'rakan',
    name: 'Rakan',
    roles: ['SUP'],
    image: getChampionImage('Rakan'),
  },
  {
    id: 'rammus',
    name: 'Rammus',
    roles: ['JGL'],
    image: getChampionImage('Rammus'),
  },
  {
    id: 'reksai',
    name: "Rek'Sai",
    roles: ['JGL'],
    image: getChampionImage('RekSai'),
  },
  { id: 'rell', name: 'Rell', roles: ['SUP'], image: getChampionImage('Rell') },
  {
    id: 'renata',
    name: 'Renata Glasc',
    roles: ['SUP'],
    image: getChampionImage('Renata'),
  },
  {
    id: 'renekton',
    name: 'Renekton',
    roles: ['TOP'],
    image: getChampionImage('Renekton'),
  },
  {
    id: 'rengar',
    name: 'Rengar',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('Rengar'),
  },
  {
    id: 'riven',
    name: 'Riven',
    roles: ['TOP'],
    image: getChampionImage('Riven'),
  },
  {
    id: 'rumble',
    name: 'Rumble',
    roles: ['TOP', 'MID'],
    image: getChampionImage('Rumble'),
  },
  {
    id: 'ryze',
    name: 'Ryze',
    roles: ['MID', 'TOP'],
    image: getChampionImage('Ryze'),
  },
  {
    id: 'samira',
    name: 'Samira',
    roles: ['ADC'],
    image: getChampionImage('Samira'),
  },
  {
    id: 'sejuani',
    name: 'Sejuani',
    roles: ['JGL'],
    image: getChampionImage('Sejuani'),
  },
  {
    id: 'senna',
    name: 'Senna',
    roles: ['SUP', 'ADC'],
    image: getChampionImage('Senna'),
  },
  {
    id: 'seraphine',
    name: 'Seraphine',
    roles: ['SUP', 'MID', 'ADC'],
    image: getChampionImage('Seraphine'),
  },
  {
    id: 'sett',
    name: 'Sett',
    roles: ['TOP', 'SUP'],
    image: getChampionImage('Sett'),
  },
  {
    id: 'shaco',
    name: 'Shaco',
    roles: ['JGL'],
    image: getChampionImage('Shaco'),
  },
  {
    id: 'shen',
    name: 'Shen',
    roles: ['TOP', 'SUP'],
    image: getChampionImage('Shen'),
  },
  {
    id: 'shyvana',
    name: 'Shyvana',
    roles: ['JGL'],
    image: getChampionImage('Shyvana'),
  },
  {
    id: 'singed',
    name: 'Singed',
    roles: ['TOP'],
    image: getChampionImage('Singed'),
  },
  { id: 'sion', name: 'Sion', roles: ['TOP'], image: getChampionImage('Sion') },
  {
    id: 'sivir',
    name: 'Sivir',
    roles: ['ADC'],
    image: getChampionImage('Sivir'),
  },
  {
    id: 'skarner',
    name: 'Skarner',
    roles: ['JGL'],
    image: getChampionImage('Skarner'),
  },
  {
    id: 'smolder',
    name: 'Smolder',
    roles: ['ADC', 'MID'],
    image: getChampionImage('Smolder'),
  },
  { id: 'sona', name: 'Sona', roles: ['SUP'], image: getChampionImage('Sona') },
  {
    id: 'soraka',
    name: 'Soraka',
    roles: ['SUP'],
    image: getChampionImage('Soraka'),
  },
  {
    id: 'swain',
    name: 'Swain',
    roles: ['SUP', 'MID', 'ADC'],
    image: getChampionImage('Swain'),
  },
  {
    id: 'sylas',
    name: 'Sylas',
    roles: ['MID'],
    image: getChampionImage('Sylas'),
  },
  {
    id: 'syndra',
    name: 'Syndra',
    roles: ['MID'],
    image: getChampionImage('Syndra'),
  },
  {
    id: 'tahmkench',
    name: 'Tahm Kench',
    roles: ['TOP', 'SUP'],
    image: getChampionImage('TahmKench'),
  },
  {
    id: 'taliyah',
    name: 'Taliyah',
    roles: ['MID', 'JGL'],
    image: getChampionImage('Taliyah'),
  },
  {
    id: 'talon',
    name: 'Talon',
    roles: ['MID', 'JGL'],
    image: getChampionImage('Talon'),
  },
  {
    id: 'taric',
    name: 'Taric',
    roles: ['SUP'],
    image: getChampionImage('Taric'),
  },
  {
    id: 'teemo',
    name: 'Teemo',
    roles: ['TOP'],
    image: getChampionImage('Teemo'),
  },
  {
    id: 'thresh',
    name: 'Thresh',
    roles: ['SUP'],
    image: getChampionImage('Thresh'),
  },
  {
    id: 'tristana',
    name: 'Tristana',
    roles: ['ADC', 'MID'],
    image: getChampionImage('Tristana'),
  },
  {
    id: 'trundle',
    name: 'Trundle',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('Trundle'),
  },
  {
    id: 'tryndamere',
    name: 'Tryndamere',
    roles: ['TOP'],
    image: getChampionImage('Tryndamere'),
  },
  {
    id: 'twistedfate',
    name: 'Twisted Fate',
    roles: ['MID'],
    image: getChampionImage('TwistedFate'),
  },
  {
    id: 'twitch',
    name: 'Twitch',
    roles: ['ADC'],
    image: getChampionImage('Twitch'),
  },
  {
    id: 'udyr',
    name: 'Udyr',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('Udyr'),
  },
  {
    id: 'urgot',
    name: 'Urgot',
    roles: ['TOP'],
    image: getChampionImage('Urgot'),
  },
  {
    id: 'varus',
    name: 'Varus',
    roles: ['ADC'],
    image: getChampionImage('Varus'),
  },
  {
    id: 'vayne',
    name: 'Vayne',
    roles: ['ADC', 'TOP'],
    image: getChampionImage('Vayne'),
  },
  {
    id: 'veigar',
    name: 'Veigar',
    roles: ['MID'],
    image: getChampionImage('Veigar'),
  },
  {
    id: 'velkoz',
    name: "Vel'Koz",
    roles: ['MID', 'SUP'],
    image: getChampionImage('Velkoz'),
  },
  { id: 'vex', name: 'Vex', roles: ['MID'], image: getChampionImage('Vex') },
  { id: 'vi', name: 'Vi', roles: ['JGL'], image: getChampionImage('Vi') },
  {
    id: 'viego',
    name: 'Viego',
    roles: ['JGL'],
    image: getChampionImage('Viego'),
  },
  {
    id: 'viktor',
    name: 'Viktor',
    roles: ['MID'],
    image: getChampionImage('Viktor'),
  },
  {
    id: 'vladimir',
    name: 'Vladimir',
    roles: ['MID', 'TOP'],
    image: getChampionImage('Vladimir'),
  },
  {
    id: 'volibear',
    name: 'Volibear',
    roles: ['TOP', 'JGL'],
    image: getChampionImage('Volibear'),
  },
  {
    id: 'warwick',
    name: 'Warwick',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('Warwick'),
  },
  {
    id: 'wukong',
    name: 'Wukong',
    roles: ['JGL', 'TOP'],
    image: getChampionImage('MonkeyKing'),
  },
  {
    id: 'xayah',
    name: 'Xayah',
    roles: ['ADC'],
    image: getChampionImage('Xayah'),
  },
  {
    id: 'xerath',
    name: 'Xerath',
    roles: ['MID', 'SUP'],
    image: getChampionImage('Xerath'),
  },
  {
    id: 'xinzhao',
    name: 'Xin Zhao',
    roles: ['JGL'],
    image: getChampionImage('XinZhao'),
  },
  {
    id: 'yasuo',
    name: 'Yasuo',
    roles: ['MID', 'TOP', 'ADC'],
    image: getChampionImage('Yasuo'),
  },
  {
    id: 'yone',
    name: 'Yone',
    roles: ['MID', 'TOP'],
    image: getChampionImage('Yone'),
  },
  {
    id: 'yorick',
    name: 'Yorick',
    roles: ['TOP'],
    image: getChampionImage('Yorick'),
  },
  {
    id: 'yuumi',
    name: 'Yuumi',
    roles: ['SUP'],
    image: getChampionImage('Yuumi'),
  },
  { id: 'zac', name: 'Zac', roles: ['JGL'], image: getChampionImage('Zac') },
  { id: 'zed', name: 'Zed', roles: ['MID'], image: getChampionImage('Zed') },
  { id: 'zeri', name: 'Zeri', roles: ['ADC'], image: getChampionImage('Zeri') },
  {
    id: 'ziggs',
    name: 'Ziggs',
    roles: ['MID', 'ADC'],
    image: getChampionImage('Ziggs'),
  },
  {
    id: 'zilean',
    name: 'Zilean',
    roles: ['SUP', 'MID'],
    image: getChampionImage('Zilean'),
  },
  { id: 'zoe', name: 'Zoe', roles: ['MID'], image: getChampionImage('Zoe') },
  { id: 'zyra', name: 'Zyra', roles: ['SUP'], image: getChampionImage('Zyra') },
];

// Mock C9 player data - In production, this would come from GRID API
// Updated 2026 LCS roster
const C9_PLAYERS = [
  {
    id: 'c9-thanatos',
    name: 'Thanatos',
    realName: 'Park Seung-gyu',
    role: 'TOP',
    image: '/images/players/thanatos.webp',
    nationality: 'KR',
  },
  {
    id: 'c9-blaber',
    name: 'Blaber',
    realName: 'Robert Huang',
    role: 'JGL',
    image: '/images/players/blaber.webp',
    nationality: 'US',
  },
  {
    id: 'c9-apa',
    name: 'APA',
    realName: 'Eain Stearns',
    role: 'MID',
    image: '/images/players/apa.jpeg',
    nationality: 'US',
  },
  {
    id: 'c9-zven',
    name: 'Zven',
    realName: 'Jesper Svenningsen',
    role: 'ADC',
    image: '/images/players/zven.webp',
    nationality: 'DK',
  },
  {
    id: 'c9-vulcan',
    name: 'Vulcan',
    realName: 'Philippe Laflamme',
    role: 'SUP',
    image: '/images/players/vulcan.webp',
    nationality: 'CA',
  },
];

// Mock statistics data for demo purposes
// In production, this would be fetched from GRID Stats Feed API
const MOCK_PLAYER_STATS: Record<string, any> = {
  'c9-thanatos': {
    playerId: 'c9-thanatos',
    gamesPlayed: 45,
    wins: 28,
    losses: 17,
    winRate: 62.2,
    kda: 3.5,
    avgKills: 3.2,
    avgDeaths: 3.1,
    avgAssists: 7.6,
    csPerMin: 8.8,
    goldPerMin: 398,
    visionScore: 35.2,
    firstBloodRate: 17.8,
    championPool: [
      {
        champion: 'Rumble',
        games: 10,
        wins: 7,
        losses: 3,
        winRate: 70.0,
        kda: 3.8,
        pickRate: 22.2,
      },
      {
        champion: "K'Sante",
        games: 8,
        wins: 5,
        losses: 3,
        winRate: 62.5,
        kda: 3.5,
        pickRate: 17.8,
      },
      {
        champion: 'Renekton',
        games: 7,
        wins: 4,
        losses: 3,
        winRate: 57.1,
        kda: 3.2,
        pickRate: 15.6,
      },
      {
        champion: 'Jayce',
        games: 6,
        wins: 4,
        losses: 2,
        winRate: 66.7,
        kda: 3.6,
        pickRate: 13.3,
      },
      {
        champion: 'Gnar',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 3.9,
        pickRate: 11.1,
      },
      {
        champion: 'Aatrox',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 3.4,
        pickRate: 11.1,
      },
      {
        champion: 'Ornn',
        games: 4,
        wins: 2,
        losses: 2,
        winRate: 50.0,
        kda: 2.8,
        pickRate: 8.9,
      },
    ],
  },
  'c9-blaber': {
    playerId: 'c9-blaber',
    gamesPlayed: 45,
    wins: 28,
    losses: 17,
    winRate: 62.2,
    kda: 4.8,
    avgKills: 4.2,
    avgDeaths: 2.8,
    avgAssists: 9.3,
    csPerMin: 6.2,
    goldPerMin: 412,
    visionScore: 42.5,
    firstBloodRate: 35.6,
    championPool: [
      {
        champion: 'Lee Sin',
        games: 12,
        wins: 8,
        losses: 4,
        winRate: 66.7,
        kda: 5.2,
        pickRate: 26.7,
      },
      {
        champion: 'Nidalee',
        games: 8,
        wins: 6,
        losses: 2,
        winRate: 75.0,
        kda: 5.8,
        pickRate: 17.8,
      },
      {
        champion: 'Viego',
        games: 7,
        wins: 4,
        losses: 3,
        winRate: 57.1,
        kda: 4.5,
        pickRate: 15.6,
      },
      {
        champion: "Rek'Sai",
        games: 6,
        wins: 4,
        losses: 2,
        winRate: 66.7,
        kda: 4.1,
        pickRate: 13.3,
      },
      {
        champion: 'Elise',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 4.9,
        pickRate: 11.1,
      },
      {
        champion: 'Jarvan IV',
        games: 4,
        wins: 2,
        losses: 2,
        winRate: 50.0,
        kda: 3.8,
        pickRate: 8.9,
      },
      {
        champion: 'Kindred',
        games: 3,
        wins: 1,
        losses: 2,
        winRate: 33.3,
        kda: 3.2,
        pickRate: 6.7,
      },
    ],
  },
  'c9-apa': {
    playerId: 'c9-apa',
    gamesPlayed: 45,
    wins: 28,
    losses: 17,
    winRate: 62.2,
    kda: 4.2,
    avgKills: 5.1,
    avgDeaths: 2.9,
    avgAssists: 7.1,
    csPerMin: 9.4,
    goldPerMin: 445,
    visionScore: 28.3,
    firstBloodRate: 22.2,
    championPool: [
      {
        champion: 'Ahri',
        games: 10,
        wins: 7,
        losses: 3,
        winRate: 70.0,
        kda: 4.8,
        pickRate: 22.2,
      },
      {
        champion: 'Azir',
        games: 8,
        wins: 5,
        losses: 3,
        winRate: 62.5,
        kda: 4.1,
        pickRate: 17.8,
      },
      {
        champion: 'Syndra',
        games: 7,
        wins: 4,
        losses: 3,
        winRate: 57.1,
        kda: 3.9,
        pickRate: 15.6,
      },
      {
        champion: 'Orianna',
        games: 6,
        wins: 4,
        losses: 2,
        winRate: 66.7,
        kda: 4.5,
        pickRate: 13.3,
      },
      {
        champion: 'Akali',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 4.2,
        pickRate: 11.1,
      },
      {
        champion: 'LeBlanc',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 4.0,
        pickRate: 11.1,
      },
      {
        champion: 'Zed',
        games: 4,
        wins: 2,
        losses: 2,
        winRate: 50.0,
        kda: 3.5,
        pickRate: 8.9,
      },
    ],
  },
  'c9-zven': {
    playerId: 'c9-zven',
    gamesPlayed: 45,
    wins: 28,
    losses: 17,
    winRate: 62.2,
    kda: 6.8,
    avgKills: 6.8,
    avgDeaths: 2.1,
    avgAssists: 7.5,
    csPerMin: 10.2,
    goldPerMin: 485,
    visionScore: 22.1,
    firstBloodRate: 15.6,
    championPool: [
      {
        champion: 'Jinx',
        games: 11,
        wins: 8,
        losses: 3,
        winRate: 72.7,
        kda: 7.8,
        pickRate: 24.4,
      },
      {
        champion: "Kai'Sa",
        games: 9,
        wins: 6,
        losses: 3,
        winRate: 66.7,
        kda: 6.5,
        pickRate: 20.0,
      },
      {
        champion: 'Aphelios',
        games: 8,
        wins: 5,
        losses: 3,
        winRate: 62.5,
        kda: 6.2,
        pickRate: 17.8,
      },
      {
        champion: 'Zeri',
        games: 6,
        wins: 4,
        losses: 2,
        winRate: 66.7,
        kda: 7.1,
        pickRate: 13.3,
      },
      {
        champion: 'Ezreal',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 5.8,
        pickRate: 11.1,
      },
      {
        champion: 'Lucian',
        games: 4,
        wins: 2,
        losses: 2,
        winRate: 50.0,
        kda: 5.2,
        pickRate: 8.9,
      },
      {
        champion: 'Varus',
        games: 2,
        wins: 0,
        losses: 2,
        winRate: 0.0,
        kda: 3.1,
        pickRate: 4.4,
      },
    ],
  },
  'c9-vulcan': {
    playerId: 'c9-vulcan',
    gamesPlayed: 45,
    wins: 28,
    losses: 17,
    winRate: 62.2,
    kda: 3.8,
    avgKills: 1.2,
    avgDeaths: 3.5,
    avgAssists: 12.1,
    csPerMin: 1.8,
    goldPerMin: 285,
    visionScore: 78.5,
    firstBloodRate: 8.9,
    championPool: [
      {
        champion: 'Nautilus',
        games: 10,
        wins: 7,
        losses: 3,
        winRate: 70.0,
        kda: 4.2,
        pickRate: 22.2,
      },
      {
        champion: 'Thresh',
        games: 8,
        wins: 5,
        losses: 3,
        winRate: 62.5,
        kda: 3.8,
        pickRate: 17.8,
      },
      {
        champion: 'Rakan',
        games: 7,
        wins: 5,
        losses: 2,
        winRate: 71.4,
        kda: 4.5,
        pickRate: 15.6,
      },
      {
        champion: 'Alistar',
        games: 6,
        wins: 4,
        losses: 2,
        winRate: 66.7,
        kda: 3.5,
        pickRate: 13.3,
      },
      {
        champion: 'Renata Glasc',
        games: 5,
        wins: 3,
        losses: 2,
        winRate: 60.0,
        kda: 3.9,
        pickRate: 11.1,
      },
      {
        champion: 'Leona',
        games: 5,
        wins: 2,
        losses: 3,
        winRate: 40.0,
        kda: 3.1,
        pickRate: 11.1,
      },
      {
        champion: 'Braum',
        games: 4,
        wins: 2,
        losses: 2,
        winRate: 50.0,
        kda: 3.2,
        pickRate: 8.9,
      },
    ],
  },
};

@Injectable()
export class PlayersService {
  private readonly logger = new Logger(PlayersService.name);

  constructor(
    private statsFeedClient: StatsFeedClient,
    private cacheService: CacheService,
  ) {}

  async getC9Players() {
    // Return C9 roster with basic info
    return {
      team: {
        id: 'c9',
        name: 'Cloud9',
        region: 'LCS',
        logo: '/images/teams/c9-logo.svg',
      },
      players: C9_PLAYERS,
    };
  }

  async getPlayerStats(playerId: string, period: string) {
    // Check cache first
    const cacheKey = `player:stats:${playerId}:${period}`;
    const cached = await this.cacheService.get(cacheKey);
    if (cached) {
      this.logger.debug(`Cache hit for ${cacheKey}`);
      return cached;
    }

    // For demo, return mock data
    // In production, use: await this.statsFeedClient.getPlayerStatistics(playerId, period);
    const stats = MOCK_PLAYER_STATS[playerId];
    if (!stats) {
      return { error: 'Player not found', playerId };
    }

    // Get player info
    const player = C9_PLAYERS.find((p) => p.id === playerId);

    const result = {
      player,
      stats,
      period,
      lastUpdated: new Date().toISOString(),
    };

    // Cache for 1 hour
    await this.cacheService.set(cacheKey, result, 3600);

    return result;
  }

  async getPlayerChampionPool(playerId: string, period: string) {
    const stats = MOCK_PLAYER_STATS[playerId];
    if (!stats) {
      return { error: 'Player not found', playerId };
    }

    const player = C9_PLAYERS.find((p) => p.id === playerId);

    return {
      player,
      championPool: stats.championPool,
      totalGames: stats.gamesPlayed,
      period,
    };
  }

  async getChampions() {
    return {
      champions: CHAMPIONS,
      count: CHAMPIONS.length,
    };
  }
}
